// Copyright IBM Corp. 2014, 2025
// SPDX-License-Identifier: MPL-2.0

package orbital

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/go-azure-helpers/lang/pointer"
	"github.com/hashicorp/go-azure-helpers/lang/response"
	"github.com/hashicorp/go-azure-helpers/resourcemanager/commonschema"
	"github.com/hashicorp/go-azure-helpers/resourcemanager/identity"
	"github.com/hashicorp/go-azure-helpers/resourcemanager/location"
	"github.com/hashicorp/go-azure-helpers/resourcemanager/resourceids"
	"github.com/hashicorp/go-azure-sdk/resource-manager/orbitalplanetarycomputer/2026-04-15/geocatalogs"
	"github.com/hashicorp/terraform-provider-azurerm/internal/sdk"
	"github.com/hashicorp/terraform-provider-azurerm/internal/services/orbital/validate"
	"github.com/hashicorp/terraform-provider-azurerm/internal/tf/pluginsdk"
	"github.com/hashicorp/terraform-provider-azurerm/internal/tf/validation"
)

//go:generate go run ../../tools/generator-tests resourceidentity

type GeoCatalogResource struct{}

var (
	_ sdk.ResourceWithUpdate   = GeoCatalogResource{}
	_ sdk.ResourceWithIdentity = GeoCatalogResource{}
)

func (r GeoCatalogResource) Identity() resourceids.ResourceId {
	return &geocatalogs.GeoCatalogId{}
}

type GeoCatalogResourceModel struct {
	Name                              string            `tfschema:"name"`
	ResourceGroupName                 string            `tfschema:"resource_group_name"`
	Location                          string            `tfschema:"location"`
	AutoGeneratedDomainNameLabelScope string            `tfschema:"auto_generated_domain_name_label_scope"`
	Tier                              string            `tfschema:"tier"`
	Tags                              map[string]string `tfschema:"tags"`
	CatalogUri                        string            `tfschema:"catalog_uri"`
}

func (r GeoCatalogResource) Arguments() map[string]*pluginsdk.Schema {
	return map[string]*pluginsdk.Schema{
		"name": {
			Type:         pluginsdk.TypeString,
			Required:     true,
			ForceNew:     true,
			ValidateFunc: validate.GeoCatalogName,
		},

		"resource_group_name": commonschema.ResourceGroupName(),

		"location": commonschema.Location(),

		"identity": commonschema.SystemAssignedUserAssignedIdentityOptional(),

		"auto_generated_domain_name_label_scope": {
			Type:         pluginsdk.TypeString,
			Optional:     true,
			ForceNew:     true,
			Default:      string(geocatalogs.AutoGeneratedDomainNameLabelScopeTenantReuse),
			ValidateFunc: validation.StringInSlice(geocatalogs.PossibleValuesForAutoGeneratedDomainNameLabelScope(), false),
		},

		"tier": {
			Type:         pluginsdk.TypeString,
			Optional:     true,
			ForceNew:     true,
			Default:      string(geocatalogs.CatalogTierBasic),
			ValidateFunc: validation.StringInSlice(geocatalogs.PossibleValuesForCatalogTier(), false),
		},

		"tags": commonschema.Tags(),
	}
}

func (r GeoCatalogResource) Attributes() map[string]*pluginsdk.Schema {
	return map[string]*pluginsdk.Schema{
		"catalog_uri": {
			Type:     pluginsdk.TypeString,
			Computed: true,
		},
	}
}

func (r GeoCatalogResource) ModelObject() interface{} {
	return &GeoCatalogResourceModel{}
}

func (r GeoCatalogResource) ResourceType() string {
	return "azurerm_orbital_geocatalog"
}

func (r GeoCatalogResource) IDValidationFunc() pluginsdk.SchemaValidateFunc {
	return geocatalogs.ValidateGeoCatalogID
}

func (r GeoCatalogResource) Create() sdk.ResourceFunc {
	return sdk.ResourceFunc{
		Timeout: 30 * time.Minute,
		Func: func(ctx context.Context, metadata sdk.ResourceMetaData) error {
			var model GeoCatalogResourceModel
			if err := metadata.Decode(&model); err != nil {
				return fmt.Errorf("decoding: %+v", err)
			}

			client := metadata.Client.Orbital.GeoCatalogsClient
			subscriptionId := metadata.Client.Account.SubscriptionId

			id := geocatalogs.NewGeoCatalogID(subscriptionId, model.ResourceGroupName, model.Name)

			if !metadata.Client.Features.SkipImportCheckOnCreateAndAllowOverwritingExistingResources {
				existing, err := client.Get(ctx, id)
				if err != nil && !response.WasNotFound(existing.HttpResponse) {
					return fmt.Errorf("checking for existing %s: %+v", id, err)
				}

				if !response.WasNotFound(existing.HttpResponse) {
					return metadata.ResourceRequiresImport(r.ResourceType(), id)
				}
			}

			expandedIdentity, err := identity.ExpandLegacySystemAndUserAssignedMap(metadata.ResourceData.Get("identity").([]interface{}))
			if err != nil {
				return fmt.Errorf("expanding `identity`: %+v", err)
			}

			autoGeneratedDomainNameLabelScope := geocatalogs.AutoGeneratedDomainNameLabelScope(model.AutoGeneratedDomainNameLabelScope)
			tier := geocatalogs.CatalogTier(model.Tier)

			geoCatalog := geocatalogs.GeoCatalog{
				Location: location.Normalize(model.Location),
				Identity: expandedIdentity,
				Properties: &geocatalogs.GeoCatalogProperties{
					AutoGeneratedDomainNameLabelScope: &autoGeneratedDomainNameLabelScope,
					Tier:                              &tier,
				},
				Tags: &model.Tags,
			}

			if err := client.CreateThenPoll(ctx, id, geoCatalog); err != nil {
				return fmt.Errorf("creating %s: %+v", id, err)
			}

			metadata.SetID(id)
			if err := pluginsdk.SetResourceIdentityData(metadata.ResourceData, &id); err != nil {
				return err
			}
			return nil
		},
	}
}

func (r GeoCatalogResource) Update() sdk.ResourceFunc {
	return sdk.ResourceFunc{
		Timeout: 30 * time.Minute,
		Func: func(ctx context.Context, metadata sdk.ResourceMetaData) error {
			client := metadata.Client.Orbital.GeoCatalogsClient

			id, err := geocatalogs.ParseGeoCatalogID(metadata.ResourceData.Id())
			if err != nil {
				return err
			}

			var model GeoCatalogResourceModel
			if err := metadata.Decode(&model); err != nil {
				return fmt.Errorf("decoding: %+v", err)
			}

			update := geocatalogs.GeoCatalogUpdate{}

			if metadata.ResourceData.HasChange("identity") {
				expandedIdentity, err := identity.ExpandLegacySystemAndUserAssignedMap(metadata.ResourceData.Get("identity").([]interface{}))
				if err != nil {
					return fmt.Errorf("expanding `identity`: %+v", err)
				}

				identityType := geocatalogs.ManagedServiceIdentityTypeNone
				switch expandedIdentity.Type {
				case identity.TypeSystemAssigned:
					identityType = geocatalogs.ManagedServiceIdentityTypeSystemAssigned
				case identity.TypeUserAssigned:
					identityType = geocatalogs.ManagedServiceIdentityTypeUserAssigned
				case identity.TypeSystemAssignedUserAssigned:
					identityType = geocatalogs.ManagedServiceIdentityTypeSystemAssignedUserAssigned
				}

				identityUpdate := &geocatalogs.ManagedServiceIdentityUpdate{
					Type: &identityType,
				}

				if len(expandedIdentity.IdentityIds) > 0 {
					userAssignedIdentities := make(map[string]geocatalogs.UserAssignedIdentity)
					for k := range expandedIdentity.IdentityIds {
						userAssignedIdentities[k] = geocatalogs.UserAssignedIdentity{}
					}
					identityUpdate.UserAssignedIdentities = &userAssignedIdentities
				}

				update.Identity = identityUpdate
			}

			if metadata.ResourceData.HasChange("tags") {
				update.Tags = &model.Tags
			}

			if err := client.UpdateThenPoll(ctx, *id, update); err != nil {
				return fmt.Errorf("updating %s: %+v", *id, err)
			}

			return nil
		},
	}
}

func (r GeoCatalogResource) Read() sdk.ResourceFunc {
	return sdk.ResourceFunc{
		Timeout: 5 * time.Minute,
		Func: func(ctx context.Context, metadata sdk.ResourceMetaData) error {
			id, err := geocatalogs.ParseGeoCatalogID(metadata.ResourceData.Id())
			if err != nil {
				return err
			}

			client := metadata.Client.Orbital.GeoCatalogsClient

			resp, err := client.Get(ctx, *id)
			if err != nil {
				if response.WasNotFound(resp.HttpResponse) {
					return metadata.MarkAsGone(id)
				}
				return fmt.Errorf("retrieving %s: %+v", *id, err)
			}

			return r.flatten(metadata, id, resp.Model)
		},
	}
}

func (r GeoCatalogResource) flatten(metadata sdk.ResourceMetaData, id *geocatalogs.GeoCatalogId, model *geocatalogs.GeoCatalog) error {
	if model == nil {
		return fmt.Errorf("retrieving %s: model was nil", id)
	}

	state := GeoCatalogResourceModel{
		Name:              id.GeoCatalogName,
		ResourceGroupName: id.ResourceGroupName,
		Location:          location.NormalizeNilable(pointer.To(model.Location)),
	}

	if model.Identity != nil {
		identityValue, err := identity.FlattenLegacySystemAndUserAssignedMap(model.Identity)
		if err != nil {
			return fmt.Errorf("flattening `identity`: %+v", err)
		}

		if err := metadata.ResourceData.Set("identity", identityValue); err != nil {
			return fmt.Errorf("setting `identity`: %+v", err)
		}
	}

	if properties := model.Properties; properties != nil {
		if properties.AutoGeneratedDomainNameLabelScope != nil {
			state.AutoGeneratedDomainNameLabelScope = string(*properties.AutoGeneratedDomainNameLabelScope)
		}

		if properties.Tier != nil {
			state.Tier = string(*properties.Tier)
		}

		if properties.CatalogUri != nil {
			state.CatalogUri = *properties.CatalogUri
		}
	}

	if model.Tags != nil {
		state.Tags = *model.Tags
	}

	if err := pluginsdk.SetResourceIdentityData(metadata.ResourceData, id); err != nil {
		return err
	}

	return metadata.Encode(&state)
}

func (r GeoCatalogResource) Delete() sdk.ResourceFunc {
	return sdk.ResourceFunc{
		Timeout: 30 * time.Minute,
		Func: func(ctx context.Context, metadata sdk.ResourceMetaData) error {
			id, err := geocatalogs.ParseGeoCatalogID(metadata.ResourceData.Id())
			if err != nil {
				return err
			}

			client := metadata.Client.Orbital.GeoCatalogsClient

			if err := client.DeleteThenPoll(ctx, *id); err != nil {
				return fmt.Errorf("deleting %s: %+v", *id, err)
			}

			return nil
		},
	}
}
